language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: NGVQeqgz8pVQtYM99qd2McMajM34HAZ7tz3TLZEDIoc0AMChRMH+Hj32tEDPDAGt5DGDwGhrvd4/j97KcFKZriO0+ZePUmUBETqECTjBH0ogXP73zU1TC6Iv1GXPkGzRu3A/glYC1BKp653/MpkkZ3KHpuGnlScQ6Jn+wCKtZULe0QSW+2SKFuFIzyTEoL/fD4M+tSUCggagRLGUteOSfy16o5DSnEIlN+i/nGmmf4mUrdxcdTMPl0qt8xEoyvomc9FfFy24AlMejShgmzofsXa5JTm9+b76m/Z6198YAZ3ut4bky052jSdNkMyoLmF/Iuw3gB79rU9xRleL7FjB+b7K1Bm7tae9ETZYl+07XDCv4VmF9hI7POtHKo4xn/Pgg8WdWVFfsUVJzt1nAyTY4t7AAvHAgS8A0gXDUXDO+SQ5+MriJZ3G2rHFjXriuiJKACUJKZ/8Q1AS95buOaKod+p4FcOjvvC/o3ErEr4x+O60mB2lrzofIH9d7v3ay6HEEWE4i5Fpg2bQBaDCt1YbFuDBr8Q6yuKYPG3x2hKW2KUXp5rnCBxmECiHVYEE+tk3KCK4wHG9MtA5MqDQzIl5dW6dZO88dKCEqKi5q9ezQruK10VBm3xWzfbx+UYtGVn32jyqNDsAk3dGT8R0FZeqAT0huBYFTWhtmW1ACmH5mUE=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: Ik/XRVEJSPCXABw13cR4cjy1LXSe3wIWWbQUpseEDxsQEgLKzAmd8dZbZIlls1m8KYcT79pT1D3lz9/jJOE9+pC2yAfNzl9/v7Vx8jYm7tJhukxBoz3s1Iip5xVjgFUfVE0bVbZZzDgVefDY2jq847nJviMPBrs3CFbdJUlXe4qfq2VWE1cyXs+WP4rRAsKJYXo2CnZbG5ewil9UjMZwzY2uOy6DQ7sBbo3oto0s0s1L/iFKlMgtPPkW0kSL1RdiUkqmSXPglmIv0QLJc0QR2RCwUJ+6DuODKKiFByZJR3m7CDX3OvqnXYUsipGUsctCcoqLlTLvH4rZsO5lZLUL0jBeGwf0OMvaHNgLw1P0nj1115ROmPV74ix3QwNR9AmP6fSxMZWp4mwFcyWhRFV9XB7QldM9vhN0nqGPuXmpvgpcqOebktWKeCTeWtRzZ/NZGovKtUAaT1yiUT1CSeuPfcwqaiUpP6e4ax28tZGeDrYsn+jraCfT4SSo3O6y0UHHktCRSzVchyxXHNa2rJFk3IczYX1vDqwHEH0T72kmgchylTLiPVbbcmDU6esj/n+ODLrYjuRkjA1kaGQxsjvzL3NK8pYvyk7iV0H+JYs4oc5b2/VvZnfkWSah2wTLKX99Os7Cqr3MTrNf/kmbduQPIIdqTUWDmaw2Za7dR9mnvzQ=
  on:
    tags: true
    repo: actano/borders-rest-client
    node: '8'
