language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: NGVQeqgz8pVQtYM99qd2McMajM34HAZ7tz3TLZEDIoc0AMChRMH+Hj32tEDPDAGt5DGDwGhrvd4/j97KcFKZriO0+ZePUmUBETqECTjBH0ogXP73zU1TC6Iv1GXPkGzRu3A/glYC1BKp653/MpkkZ3KHpuGnlScQ6Jn+wCKtZULe0QSW+2SKFuFIzyTEoL/fD4M+tSUCggagRLGUteOSfy16o5DSnEIlN+i/nGmmf4mUrdxcdTMPl0qt8xEoyvomc9FfFy24AlMejShgmzofsXa5JTm9+b76m/Z6198YAZ3ut4bky052jSdNkMyoLmF/Iuw3gB79rU9xRleL7FjB+b7K1Bm7tae9ETZYl+07XDCv4VmF9hI7POtHKo4xn/Pgg8WdWVFfsUVJzt1nAyTY4t7AAvHAgS8A0gXDUXDO+SQ5+MriJZ3G2rHFjXriuiJKACUJKZ/8Q1AS95buOaKod+p4FcOjvvC/o3ErEr4x+O60mB2lrzofIH9d7v3ay6HEEWE4i5Fpg2bQBaDCt1YbFuDBr8Q6yuKYPG3x2hKW2KUXp5rnCBxmECiHVYEE+tk3KCK4wHG9MtA5MqDQzIl5dW6dZO88dKCEqKi5q9ezQruK10VBm3xWzfbx+UYtGVn32jyqNDsAk3dGT8R0FZeqAT0huBYFTWhtmW1ACmH5mUE=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: q803sSxC52HO+0hQbre48/l0mVusU4m8KP/T8jMPMM2d9ELRFG/W9cdQsgdaRHKOKJABE7vVAg4O1N2rK7Um3olUMoeEXnmB824hDUCAi8ZPt5sN0lhAU0KI/84k+CD3VpzZ4kY6rgfFp4u8Zlz6TjPZ8SWU4VgEw3KVfxsgVS1vHT4HVXTiRD5PdyJ5+aABROD3x5vZ6FnPWyFB6JhZfyV7/i+6Z+6EA2umRmnKvP9Iu147sk/2L9Vdj16H+ZkJLoa/mvzPzVbHdz6nUXXNhvXuDtFyU5y8ro6KZReI9ZRwFJA19bfNTGVzT1Z+oQhDRlDHofoIL1LymBsyWnYuh2Vpy68mF0K13defTeVi5N2iHOSdEC6arOLnT++DTkynPfm9Xml21+iEztmWrBtzIZGBwGGc5Bhlt9tnN5UutBxYAHc51bNhsXYlXhVMts6bAP2WqntbAIYnn2iqpQwLcAbkfUzOtQ2ibrnfBdqq3J+E1uv+x2f0m6Zpdqcoa0gazuqQ2zE+Gseuf+/YldK2q4lxhtZyGiYFQEbI2rz5ChXWrFZAkAwmg6nmJaKGXRQASvcRg8UD9EDPebdLkpF4bqKoY/xmDFwg+XLdWEUoVmeaFIiO2QkQJoLa2sYA4PAW1zcs3F+2UA12R4t1UDa90HrxsQhRTuJdFHbW0lrfHGQ=
  on:
    tags: true
    repo: actano/borders-rest-client
    node: '8'
