language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: NGVQeqgz8pVQtYM99qd2McMajM34HAZ7tz3TLZEDIoc0AMChRMH+Hj32tEDPDAGt5DGDwGhrvd4/j97KcFKZriO0+ZePUmUBETqECTjBH0ogXP73zU1TC6Iv1GXPkGzRu3A/glYC1BKp653/MpkkZ3KHpuGnlScQ6Jn+wCKtZULe0QSW+2SKFuFIzyTEoL/fD4M+tSUCggagRLGUteOSfy16o5DSnEIlN+i/nGmmf4mUrdxcdTMPl0qt8xEoyvomc9FfFy24AlMejShgmzofsXa5JTm9+b76m/Z6198YAZ3ut4bky052jSdNkMyoLmF/Iuw3gB79rU9xRleL7FjB+b7K1Bm7tae9ETZYl+07XDCv4VmF9hI7POtHKo4xn/Pgg8WdWVFfsUVJzt1nAyTY4t7AAvHAgS8A0gXDUXDO+SQ5+MriJZ3G2rHFjXriuiJKACUJKZ/8Q1AS95buOaKod+p4FcOjvvC/o3ErEr4x+O60mB2lrzofIH9d7v3ay6HEEWE4i5Fpg2bQBaDCt1YbFuDBr8Q6yuKYPG3x2hKW2KUXp5rnCBxmECiHVYEE+tk3KCK4wHG9MtA5MqDQzIl5dW6dZO88dKCEqKi5q9ezQruK10VBm3xWzfbx+UYtGVn32jyqNDsAk3dGT8R0FZeqAT0huBYFTWhtmW1ACmH5mUE=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: VRka8RyBazyNI1n3I1eMaQJNtaphr43Fw6ysAljodVPZ4ZXQ4qwazGMO4V17TCd9AaS8JpLhJENCpeSdKJx4f9t3zsUi0x9G/J1zaIc420bq1LlK6tC/ummUTYH63RLXqrRU6L7C++/fFQj/EvDW4frOc+UHJUoUzQdR+q50rZMlubPmiApAxVn6PytM+BeL3zL8vAmJ6/GGfZWAMHFCr3AtS8h5UsANThnEcIunB6xSVVkZvSmhSVyksLbSBb8PaZexoVw4VYETnmhrP8xoLe/Mm9y4W3EAC2nfw9PvBRW5WHgFFh0NgNTtlfds7dsbxULWnM5VxjZz1OoAUz8WL3gkMi0vsfD/kJMJxL9PFZjnpS45WEFom0pc8fijI4TT3I5zhXepVdaKuRvDVB3jhjjw6it0yai8J/CJvb0DO5AMAcl5l6e/tBA37o/QtdmYTvbCSiZPDbsSiyd/081zAtfXjqQAR1z/zV0vUBQLeS3X7ze33BF6BuanifJzntTN5l65ftyBCYihspgzboTECpH+50MI1eO2z3oz87Qplbo6X5X8xTZaE4ctGSFXl2F/uhMmX7Y/Z2j+BZZJI4CErpl7V+BZIhh64qUzX9TWb4lSmWBVzlOETZu08CT47pVAdlqsTs4uv8L85BhTrf1rq+GuMdRbr0HuicYGSNmNbOk=
  on:
    tags: true
    repo: actano/borders-rest-client
    node: '8'
