export { default as get, GET } from './get'
export { default as post, POST } from './post'
export { default as del, DELETE } from './delete'
export { default as put, PUT } from './put'
export { default as patch, PATCH } from './patch'
